# To set up PostgreSQL on Mac...
#
# Install Postregs.app (http://postgresapp.com/)
# Due to this bug: https://github.com/PostgresApp/PostgresApp/issues/112
# Install this beta release: https://s3-eu-west-1.amazonaws.com/eggerapps.at/postgresapp/PostgresApp-9.2.4.3-Beta2.zip
# Unzip and drag to Postgres to the Applictions folder and run it (an elephant should appear in your status bar)
#
# add to your .bash_profile:
# export PATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
#
# Then from the command line:
# createuser -s -r villagecraft -h localhost
# rake db:create
# rake db:reset (OR rake db:schema:load for an empty db with no seed data)
#
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: villagecraft_development
  username: villagecraft
  password: 
  su_username: villagecraft
  su_password: 

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: villagecraft_test
  username: villagecraft
  password: 
  su_username: villagecraft
  su_password: 

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: villagecraft_production
  username: villagecraft
  password: supersecret
  su_username: villagecraft
  su_password: supersecret
