class_options:
  Event:
    max_attendees:
      type: number
      min: 1
      clear: false
    price:
      type: number
      step: 1
      min: 0
    external_url:
      type: text
      title: 'External URL'
      placeholder: URL of external event
    venue_uuid:
      type: select
      title: Venue
      emptytext: TBD
      sourceCache: true
      inputclass: 'margin-top-5'
      